version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: catalago-db
      POSTGRES_USER: catalago-db
      POSTGRES_DB: catalago-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    networks:
      - mynetwork
    ports:
      - "5446:5432"
networks:
  mynetwork:
volumes:
  postgres-data:
